apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - configmap.yaml
  - services.yaml
  - statefulset.yaml
  - pdb.yaml
labels:
  - pairs:
      app.kubernetes.io/name: when
      app.kubernetes.io/part-of: when
