package com.when.ingress.grpc;

import com.when.ingress.application.ForwardingContext;
import io.grpc.Context;
import io.grpc.Contexts;
import io.grpc.Metadata;
import io.grpc.ServerCall;
import io.grpc.ServerCallHandler;
import io.grpc.ServerInterceptor;
import io.grpc.Status;

/** Restores the identity generated by the ingress node for an internal forwarded Submit. */
public final class ForwardingServerInterceptor implements ServerInterceptor {
    static final Metadata.Key<String> MESSAGE_ID =
            Metadata.Key.of("x-when-forwarded-message-id", Metadata.ASCII_STRING_MARSHALLER);
    static final Metadata.Key<String> TRACE_ID =
            Metadata.Key.of("x-when-forwarded-trace-id", Metadata.ASCII_STRING_MARSHALLER);
    static final Metadata.Key<String> TIME_WHEEL_ID =
            Metadata.Key.of("x-when-forwarded-time-wheel-id", Metadata.ASCII_STRING_MARSHALLER);

    @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
            ServerCall<ReqT, RespT> call,
            Metadata headers,
            ServerCallHandler<ReqT, RespT> next) {
        String messageId = headers.get(MESSAGE_ID);
        String traceId = headers.get(TRACE_ID);
        String timeWheelId = headers.get(TIME_WHEEL_ID);
        boolean absent = messageId == null && traceId == null && timeWheelId == null;
        boolean complete = hasText(messageId) && hasText(traceId) && hasText(timeWheelId);
        if (!absent && !complete) {
            call.close(Status.INVALID_ARGUMENT.withDescription("forwarded routing identity is incomplete"), new Metadata());
            return new ServerCall.Listener<>() {
            };
        }
        if (absent) {
            return next.startCall(call, headers);
        }
        Context context = ForwardingContext.withIdentity(
                Context.current(), messageId, traceId, timeWheelId);
        return Contexts.interceptCall(context, call, headers, next);
    }

    private static boolean hasText(String value) {
        return value != null && !value.isBlank();
    }
}
